<?php

namespace App\Http\Controllers;

use App\Models\Medias;
use App\Models\Posts;
use App\Models\Products;
use Illuminate\Database\Eloquent\Relations\MorphToMany;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;

class PostsController extends Controller
{
   protected string $module ='posts';
   public function index(Request $request)
   {
       $post = Posts::with('gallery')->with('category')->find(1);
//       dd($post);

       $s = $request->input('s');
       $pageSize = $request->input('page_size') ?? 5;
       $selectStatus = DB::raw('if(status = 1, "Hoạt động", "Tạm dừng") as status_label');
       $objs = Posts::select('*', $selectStatus)
            ->where('name', 'like', "%{$s}%")
           ->where('code', 'like', "%{$s}%")
           ->with('avatar')
           ->with('gallery')
           ->paginate($pageSize);
       return response()->json($objs);
//       return parent::index($request); // TODO: Change the autogenerated stub
   }
    public function edit($id)
    {
        $obj = Posts::with('gallery')->with('category')->find($id);

        return response()->json([
            'result' => $obj,
            'status' => true
        ]);
    }
    public function store(Request $request)
    {
        $this->baseServices->validate($request, $this->module);
        $obj = DB::table($this->module)->insert($request->all());
        return $obj;
    }
    public function addMedia()
    {
//      $posts->medias()->attach($request->medias);
$posts =Posts::find(1);
//dd($posts);
      $posts->gallery()->sync([1,2]);
//      $posts->medias()->sync([]);

        return 'Success';
    }
}
