<?php

namespace App\Http\Controllers;

use App\Http\Requests\PostRequest;
use App\Models\Medias;
use App\Models\Posts;
use App\Models\Products;
use Illuminate\Database\Eloquent\Relations\MorphToMany;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;

class PostsController extends Controller
{
    protected string $module = 'posts';

    public function index(Request $request)
    {
        $s = $request->input('s');
        $currentPage = $request->input('current');
        $pageSize = $request->input('page_size') ?? 5;
        $selectStatus = DB::raw('if(status = 1, "Hoạt động", "Tạm dừng") as status_label');
        $objs = Posts::select('*', $selectStatus)
            ->where('name', 'like', "%{$s}%")
            ->where('code', 'like', "%{$s}%")
            ->with('avatar')
            ->with('gallery')
            ->paginate($pageSize, ['*'], 'page', $currentPage);
        return response()->json($objs);
//       return parent::index($request); // TODO: Change the autogenerated stub
    }

    public function edit($id)
    {
        $categories = DB::table('categories')->select('id as value', 'name as label')->get();

        $obj = Posts::with('gallery')
            ->with('avatar')
            ->with('category')
            ->find($id);

        return response()->json([
            'result' => $obj,
            'expand' => [
                'categories' => $categories,
            ],
            'status' => true
        ]);
    }

    public function store(PostRequest $request)
    {
//        $this->baseServices->validate($request, $this->module);
        $obj = DB::table($this->module)->insert($request->all());
        return $obj;
    }

    public function update(PostRequest $request, $id)
    {
        $posts = Posts::find($id);

        $galleryIds = $request->input('media_ids');
        if ($galleryIds) {
            $posts->gallery()->sync($galleryIds);
        }

        $request->except('gallery');
        $params = $request->except(['media_ids', 'gallery']);

        $res = Posts::where('id', $id)->update($params);

        return response()->json(['status' => true, 'result' => $res]);
    }
}
