<?php

namespace App\Http\Controllers;

use App\Models\Posts;
use App\Models\Products;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;

class ProductsController extends Controller
{

    protected string $module = 'products';

    public function index(Request $request)
    {
        $s = $request->input('s');
        $pageSize = $request->input('page_size') ?? 5;
        $selectStatus = DB::raw('if(status = 1, "Hoạt động", "Tạm dừng") as status_label');
        $objs = Products::select('*', $selectStatus)
            ->where('name', 'like', "%{$s}%")
            ->where('code', 'like', "%{$s}%")
//           ->with('category')
            ->paginate($pageSize);
        return response()->json($objs);
//       return parent::index($request); // TODO: Change the autogenerated stub
    }

}
