version: "2"
services:
    nginx:
        image: nginx
        container_name: sayo-nginx
        volumes:
            - ./_docker/nginx/app.conf:/etc/nginx/conf.d/default.conf
            - ./:/var/www/html
        ports:
            - 8088:80
        links:
            - php:php
    php:
        build: _docker/php
        container_name: sayo-php
        expose:
            - "9000"
        links:
            - mysql
        volumes:
            - ./:/var/www/html
            - ./_docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    mysql:
        image: mysql:5.7
        command: --default-authentication-plugin=mysql_native_password
        container_name: 39mail-mysql
        volumes:
            - ./_docker/data/mysql-5.7:/var/lib/mysql
        ports:
            - 8084:3306
        environment:
            MYSQL_DATABASE: 'sayo'
            MYSQL_ROOT_PASSWORD: 'secret'
            MYSQL_USER: 'user'
            MYSQL_PASSWORD: 'pass'
